FROM ubuntu:22.04 

RUN printf 'Acquire::http::Pipeline-Depth 0;\n\
Acquire::http::No-Cache true;\n\
Acquire::BrokenProxy    true;'\
>> /etc/apt/apt.conf.d/99fixbadproxy

RUN export DEBIAN_FRONTEND=noninteractive \
 && export DBUS_SESSION_BUS_ADDRESS=/dev/null \
 && apt-get update \
 && apt-get install --yes locales \
                          git \
                          curl \
                          autoconf \
                          bison \
                          build-essential \
                          libssl-dev \
                          libyaml-dev \
                          libreadline6-dev \
                          zlib1g-dev \
                          libncurses5-dev \
                          libffi-dev \
                          libgdbm6 \
                          libgdbm-dev \
                          libdb-dev \
                          uuid-dev \
                          libpq-dev \
 && apt autoremove -y \
 && rm -rf /var/lib/apt/lists/* \
 && rm -rf /var/cache/apt/archives/* \
 && rm -rf /var/lib/apt/lists/partial/* \
 && locale-gen en_US.UTF-8 
 
RUN git clone https://github.com/rbenv/ruby-build.git \
 && PREFIX=/usr/local ./ruby-build/install.sh \
 && ruby-build truffleruby+graalvm-22.2.0  /usr/local/truffleruby+graalvm-22.2.0

ENV PATH=$PATH:/usr/local/truffleruby+graalvm-22.2.0/bin \
    LANG=en_US.UTF-8

RUN gem install rails

RUN mkdir -p /order-creation && cd /order-creation \
 && rails new /order-creation --api --skip-bundle --skip-git --database=postgresql \
 && sed -i 's/gem \"tzinfo-data\", platforms: %i\[ mingw mswin x64_mingw jruby \]/gem "tzinfo-data"/g' Gemfile \
 && bundle install

WORKDIR /order-creation 
